# Generated by Django 5.2.7 on 2025-10-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': '1.Kategoriyalar'},
        ),
    ]
