# Generated by Django 5.2.7 on 2025-10-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentariya', 'verbose_name_plural': '2.Komentariyalar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': '3.Kontaktlar'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Yanglik', 'verbose_name_plural': '4.Yangliklar'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Subscribe', 'verbose_name_plural': '5.Subscribes'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_manu',
            new_name='is_menu',
        ),
    ]
