# Generated by Django 5.2.7 on 2025-11-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otp_alter_category_slug_alter_new_views_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
